import { useEffect, useState } from "react";
import Head from "next/head";
import { BaseConcept } from "../components/BaseConcept";
import Content from "../components/Content";
import { Footer } from "../components/Footer";
import Hero from "../components/Hero";
import MetaHead from "../components/MetaHead";
import NavBar from "../components/NavBar";
import { OurPartners } from "../components/OurPartners";
import Subscribe from "../components/Subscribe";
import { ThreeCards } from "../components/ThreeCards";
import AboutUs from "../components/AboutUs";

export default function Home() {
  const [windowSize, setWindowSize] = useState({
    width: undefined,
    height: undefined,
  });

  const [isMobile, setMobile] = useState(false);

  useEffect(() => {
    const handleSize = () => {
      setWindowSize({
        width: window.innerWidth,
        heigth: window.innerHeight,
      });
    };
    window.addEventListener("resize", handleSize);
    handleSize();
    return () => window.removeEventListener("resize", handleSize);
  }, []);

  useEffect(() => {
    if (windowSize.width < 500) {
      setMobile(true);
    } else {
      setMobile(false);
    }
  }, [windowSize]);

  <Head>
        <title>title</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

  return (
    <>
     
<MetaHead/>
      <div className=" font-poppins overflow-auto overflow-x-hidden text-white h-screen px-4 md:px-20 py-8 bg-gradient-to-b from-background to-background ">
        <NavBar isMobile={isMobile} />
        <Hero />
        <AboutUs/>
        <Content />
        <BaseConcept />
        <ThreeCards />
        <OurPartners />
        <Subscribe/>
        <Footer />
      </div>
    </>
  );
}
